print("",end=" "*7)
print("A")
print("",end=" "*6)
print("B B")
print("",end=" "*5)
print("C   C")
print("",end=" "*4)
print("D     D")
print("",end=" "*3)
print("E       E")
print("",end=" "*4)
print("D     D")
print("",end=" "*5)
print("C   C")
print("",end=" "*6)
print("B B")
print("",end=" "*7)
print("A")