co8 = ('Palmeiras', 'Cruzeiro', 'Grêmio', 'Santos', 'Corinthias', 'Flamengo', 'Atlético M', 'Atlético P')
co16 = ('Internacional', 'Chapecoense', 'Botafogo', 'São Paulo', 'Fluminense', 'Vasco', 'Bahia', 'Sport')
co20 = ('Vitória', 'Ponte Preta', 'América', 'Coritiba')
top20 = co8 + co16 + co20
print("=" * 100)
print(f"{'Brasileirão 2019':^100}")
print("=" * 100)
print(f"Lista dos Times: {top20}")
print("-=-"*20)
print(f"Os 5 primeiros são {top20[:6]}")
print("-=-"*20)
print(f"Os 4 últimos são {top20[-4:]}")
print("-=-"*20)
print(f"E a Chapecoense está na {top20.index('Chapecoense')+1}º.")